* Bài 3.1: 

In [2]:
import numpy as np
# Hiển thị phiên bản Numpy
print(f'Phiền bản Numpy: {np.__version__}','\n')

# Hiển thị cấu trúc xây dựng của Numpy: 
print('Cấu trúc xây dựng của numpy: ','\n')
print(np.show_config())




Phiền bản Numpy: 2.3.4 

Cấu trúc xây dựng của numpy:  

{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35217",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.4",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35217",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.30",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0fv2o5t8/cp313-win_amd64/build/venv/Lib/si

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


* Bài 3.2: 

In [3]:
# 1: Tạo numpy gtr 0 -> 9, hiện thị phần tử , kiểu dữ liệu, kích thước: 
import numpy as np
import numpy.ma as ma
arr_1 = np.arange(10)

print(f'Các phần tử có trong arr_1: {arr_1}')
print(f'Kiểu sữ liệu arr_1: {arr_1.dtype}')
print(f'Kích thước của arr_1: {arr_1.shape}','\n')

# 2: Tạo arr_odd, arr_even: 
arr_odd = arr_1[arr_1 % 2 != 0]
arr_even = arr_1[arr_1 % 2 == 0]

print(f'Mảng con của arr_1 chứa các phần tử lẻ: {arr_odd}','\n')
print(f'Mảng con của arr_1 chứa các phần tử chẵn: {arr_even}','\n')

# 3: Tạo arr_update với các phần tử chẵn giữ nguyên các phần tử lẻ thay bằng 100
# Cách 1: np.where()
arr_update_1 = np.where(arr_1 % 2 != 0, 100, arr_1)
print(f'Mảng arr_update_1: {arr_update_1}')


# Cách 2: 
arr_update_2 = arr_1
for i in arr_update_2:
    if i % 2 != 0:
        arr_update_2[i] = 100
print(f'Mảng arr_update_2: {arr_update_2}')








Các phần tử có trong arr_1: [0 1 2 3 4 5 6 7 8 9]
Kiểu sữ liệu arr_1: int64
Kích thước của arr_1: (10,) 

Mảng con của arr_1 chứa các phần tử lẻ: [1 3 5 7 9] 

Mảng con của arr_1 chứa các phần tử chẵn: [0 2 4 6 8] 

Mảng arr_update_1: [  0 100   2 100   4 100   6 100   8 100]
Mảng arr_update_2: [  0 100   2 100   4 100   6 100   8 100]


* Bài 3.3: 
    

In [4]:
import numpy as np
arr_a = [1,2,3,4,5,6]

arr_b = [7,2,10,2,7,4,9,4,9,8]


In [5]:
# 1 Tạo arr_c chỉ lấy duy nhất các phần tử xuất hiện ở cả arr_a, arr_b :

arr_c = np.intersect1d(arr_a, arr_b) # Phép giao 
print(f'Arr_c chứa các ptu chỉ xuất hiện cả ở arr_a, arr_b: {arr_c}')
# Phép hợp dùng union1d()

# 2: Tạo arr_d chứa các phần tử chỉ xuất hiện ở arr_a: 
arr_d = []
for i in arr_a + arr_b: 
    if i in arr_a: 
        arr_d.append(i)
print(f'Arr_d chỉ chứa các phần tử xuất hiện ở arr_a: {arr_d}')

# 3: 
arr_e = np.array([2,6,1,9,10,3,27,8,6,25,16])
arr_f = []
for i in range(len(arr_e)): 
    if 5 <= arr_e[i] <= 10:
        arr_f.append(arr_e[i])

print(f'Arr_f chỉ chứa các phtu có gtri 5 -> 10: {arr_f}')


Arr_c chứa các ptu chỉ xuất hiện cả ở arr_a, arr_b: [2 4]
Arr_d chỉ chứa các phần tử xuất hiện ở arr_a: [1, 2, 3, 4, 5, 6, 2, 2, 4, 4]
Arr_f chỉ chứa các phtu có gtri 5 -> 10: [np.int64(6), np.int64(9), np.int64(10), np.int64(8), np.int64(6)]


* Bài 3.4: 

In [6]:
import numpy as np
# 1: Tạo arr_zeros có 10 ptu 0, cập nhật ptu ở vtri 5 là 1 
print("Ý 1: ",'\n')
arr_zeros = np.zeros(10, dtype=int)
print(f'Arr_zeros: {arr_zeros}')
# Cập nhật phần tử: 
arr_zeros[5] = 1
print(f'Arr_zeros sau khi cập nhật {arr_zeros}','\n')

# 2: 
print("Ý 2: ",'\n')
arr_h = np.arange(10, 25)
print(f'Arr_h trước khi đảo ngược: {arr_h}')
print(f'Arr_h sau khi đảo ngược: {arr_h[::-1]}','\n')

# 3: 
print("Ý 3: ",'\n')
# Cách 1:  Boolean indexing
arr_k = np.array([1,2,0,8,2,0,1,3,0,5,0])

arr_1 = arr_k[arr_k != 0]
print('Mảng các phần tử khác 0: ','\n')
print(arr_1)
# Cách 2: 
arr_1_2 = arr_k[np.where(arr_k != 0)]
print(arr_1_2)

# Cách 3: 
arr_1_3 = arr_k[np.nonzero(arr_k != 0)]
print(arr_1_3,'\n')

# 4: 
print("Ý 4: ",'\n')
arr_1 = np.append(arr_1, [10,20])
print('Thêm phần tử 10, 20 và cuối dãy của  arr_1: ')
print(arr_1,'\n')

# 5: 
print("Ý 5: ",'\n')
arr_1[5] = 100
print('Thêm ptu có gtri 100 và vtr có index là 5: ')
print(arr_1,'\n')

# 6: 
print("Ý 6: ",'\n')
print('Mảng gốc: ')
print(arr_1,'\n')
arr_1 = np.delete(arr_1, [0,1,2])
print('Mảng sau khi xóa các ptu ở vtr [0,1,2]: ')
print(arr_1)


Ý 1:  

Arr_zeros: [0 0 0 0 0 0 0 0 0 0]
Arr_zeros sau khi cập nhật [0 0 0 0 0 1 0 0 0 0] 

Ý 2:  

Arr_h trước khi đảo ngược: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Arr_h sau khi đảo ngược: [24 23 22 21 20 19 18 17 16 15 14 13 12 11 10] 

Ý 3:  

Mảng các phần tử khác 0:  

[1 2 8 2 1 3 5]
[1 2 8 2 1 3 5]
[1 2 8 2 1 3 5] 

Ý 4:  

Thêm phần tử 10, 20 và cuối dãy của  arr_1: 
[ 1  2  8  2  1  3  5 10 20] 

Ý 5:  

Thêm ptu có gtri 100 và vtr có index là 5: 
[  1   2   8   2   1 100   5  10  20] 

Ý 6:  

Mảng gốc: 
[  1   2   8   2   1 100   5  10  20] 

Mảng sau khi xóa các ptu ở vtr [0,1,2]: 
[  2   1 100   5  10  20]


* Bài 3.5: 

In [7]:

# Lấy file txt về heights, weights: 
list_heights = []
list_weights = []

# Lấy file heights_1.txt: 
with open('heights_1.txt', 'r') as f: 
    for line in f: 
        list_heights.append(float(line))
print(list_heights)


# Lấy weights_1.txt: 
with open('weights_1.txt', 'r') as f: 
    for line in f: 
        list_weights.append(float(line))
print(list_weights)

[75.0, 77.0, 75.0, 77.0, 72.0, 77.0, 73.0, 71.0, 74.0, 70.0, 68.0, 78.0, 76.0, 70.0, 73.0, 76.0, 71.0, 77.0, 71.0, 72.0, 77.0, 77.0, 74.0, 73.0, 77.0, 68.0, 74.0, 72.0, 68.0, 76.0, 78.0, 74.0, 78.0, 72.0, 70.0, 68.0, 68.0, 77.0, 77.0, 71.0, 68.0, 76.0, 74.0, 76.0, 77.0, 68.0, 72.0, 69.0, 70.0, 74.0]
[161.0, 178.0, 240.0, 190.0, 193.0, 233.0, 213.0, 184.0, 166.0, 188.0, 217.0, 182.0, 221.0, 202.0, 171.0, 184.0, 192.0, 210.0, 184.0, 234.0, 217.0, 192.0, 215.0, 162.0, 223.0, 193.0, 217.0, 176.0, 166.0, 210.0, 205.0, 223.0, 175.0, 184.0, 214.0, 170.0, 203.0, 176.0, 167.0, 213.0, 186.0, 207.0, 230.0, 210.0, 213.0, 200.0, 169.0, 173.0, 221.0, 231.0]


In [8]:
# 1 : Tạo numpy.array từ heights: 
arr_heights = np.array(list_heights)
print('Danh sách chiều cao: ')
print(arr_heights,'\n')

# 2: Tạo Numpy.array từ weights: 
arr_weights = np.array(list_weights)
print('Danh sách cân nặng: ')
print(arr_weights,'\n')


Danh sách chiều cao: 
[75. 77. 75. 77. 72. 77. 73. 71. 74. 70. 68. 78. 76. 70. 73. 76. 71. 77.
 71. 72. 77. 77. 74. 73. 77. 68. 74. 72. 68. 76. 78. 74. 78. 72. 70. 68.
 68. 77. 77. 71. 68. 76. 74. 76. 77. 68. 72. 69. 70. 74.] 

Danh sách cân nặng: 
[161. 178. 240. 190. 193. 233. 213. 184. 166. 188. 217. 182. 221. 202.
 171. 184. 192. 210. 184. 234. 217. 192. 215. 162. 223. 193. 217. 176.
 166. 210. 205. 223. 175. 184. 214. 170. 203. 176. 167. 213. 186. 207.
 230. 210. 213. 200. 169. 173. 221. 231.] 



In [9]:
# 3: Quy đổi hệ số chiều cao: 
m = 0.0254
arr_heights_m = arr_heights * m
print('Đổi hệ số từ inch sang đơn vị (mét): ')
print(arr_heights_m)





Đổi hệ số từ inch sang đơn vị (mét): 
[1.905  1.9558 1.905  1.9558 1.8288 1.9558 1.8542 1.8034 1.8796 1.778
 1.7272 1.9812 1.9304 1.778  1.8542 1.9304 1.8034 1.9558 1.8034 1.8288
 1.9558 1.9558 1.8796 1.8542 1.9558 1.7272 1.8796 1.8288 1.7272 1.9304
 1.9812 1.8796 1.9812 1.8288 1.778  1.7272 1.7272 1.9558 1.9558 1.8034
 1.7272 1.9304 1.8796 1.9304 1.9558 1.7272 1.8288 1.7526 1.778  1.8796]


In [10]:
# 4: Quy đổi hệ số cân nặng: 
kg = 0.453592
arr_weights_kg = arr_weights * kg
print('Đổi hệ số từ pound sang đơn vị (kg): ')
print(arr_weights_kg)

Đổi hệ số từ pound sang đơn vị (kg): 
[ 73.028312  80.739376 108.86208   86.18248   87.543256 105.686936
  96.615096  83.460928  75.296272  85.275296  98.429464  82.553744
 100.243832  91.625584  77.564232  83.460928  87.089664  95.25432
  83.460928 106.140528  98.429464  87.089664  97.52228   73.481904
 101.151016  87.543256  98.429464  79.832192  75.296272  95.25432
  92.98636  101.151016  79.3786    83.460928  97.068688  77.11064
  92.079176  79.832192  75.749864  96.615096  84.368112  93.893544
 104.32616   95.25432   96.615096  90.7184    76.657048  78.471416
 100.243832 104.779752]


In [11]:
# 5: Tính BMI: 
arr_bmi = arr_weights_kg/ (arr_heights_m * arr_heights_m)
print('Tính chỉ số BMI: ')
print(arr_bmi)

Tính chỉ số BMI: 
[20.12339733 21.10748576 29.99761093 22.53046233 26.1752157  27.6294617
 28.10165102 25.66250687 21.31290267 26.97489248 32.99437161 21.03197882
 26.90066661 28.98366107 22.5604804  22.3969351  26.77826804 24.90208995
 25.66250687 31.73575375 25.73215961 22.76762509 27.60406069 21.37308669
 26.44364789 29.34522452 27.86084265 23.86962675 25.23993404 25.56171941
 23.68986625 28.63118853 20.22305655 24.95460979 30.70546272 25.84812523
 30.86570248 20.870323   19.80309058 29.7071411  28.28088995 25.19655199
 29.52992539 25.56171941 25.25783409 30.40955909 22.9202666  25.54735099
 31.70984701 29.65831637]


In [12]:
# 6: Gtr ở index = 50 của arr_weights_kg: 
idx = arr_weights_kg[-1]

print(f'Gtri cân nặng ở vtr index = 50: {idx}')

Gtri cân nặng ở vtr index = 50: 104.779752


In [13]:
# 7: Tạo arr_heights_m_20 gồm các phần tử có idx từ 20 -> 40: 
arr_heights_20 = arr_heights_m[20:41]
print('Mảng gồm các ptu từ index 20 -> 40: ')
print(arr_heights_20)

Mảng gồm các ptu từ index 20 -> 40: 
[1.9558 1.9558 1.8796 1.8542 1.9558 1.7272 1.8796 1.8288 1.7272 1.9304
 1.9812 1.8796 1.9812 1.8288 1.778  1.7272 1.7272 1.9558 1.9558 1.8034
 1.7272]


In [14]:
# 8: Cho biết cầu thủ bóng chày có BMI < 21 trong arr_bmi : 
arr_bmi_21 = arr_bmi[arr_bmi < 21]
print('Các cầu thủ bóng chày có bmi < 21: ')
print(arr_bmi_21)

Các cầu thủ bóng chày có bmi < 21: 
[20.12339733 20.22305655 20.870323   19.80309058]


In [15]:
# 9: 
# Trung bình chiều cao các cầu thủ: 
heights_tb = sum(arr_heights_m) / len(arr_heights_m)
print(f'Chiều cao TB các cầu thủ: {heights_tb:.2f}')


# Trung bình cân nặng của các cầu thủ: 
weights_tb = sum(arr_weights_kg)/ len(arr_weights_kg)
print((f'Cân nặng TB các cầu thủ : {weights_tb:.2f}'))



Chiều cao TB các cầu thủ: 1.86
Cân nặng TB các cầu thủ : 89.67


In [16]:
# 10: Tính chiều cao, cân nặng max : 
max_idx_m = np.argmax(arr_heights_m) # Trả về index chứ không trả về gtr
max_idx_kg = np.argmax(arr_weights_kg)
print(f'Cầu thủ cao nhất: {arr_heights_m[max_idx_m]:.2f}','\n')
print(f'Cầu thủ nặng nhất: {arr_weights_kg[max_idx_kg]:.2f}')



Cầu thủ cao nhất: 1.98 

Cầu thủ nặng nhất: 108.86


In [17]:
# 11: Tính chiều cao, cân nặng min: 
mix_idx_m = np.argmin(arr_heights_m)
min_idx_kg = np.argmin(arr_weights_kg)
print(f'Cầu thủ thấp nhất: {arr_heights_m[mix_idx_m]:.2f}')
print(f'Cầu thủ nhẹ nhất: {arr_weights_kg[min_idx_kg]:.2f}')

Cầu thủ thấp nhất: 1.73
Cầu thủ nhẹ nhất: 73.03


* Bài 3.6: 

- 1: 

In [18]:
import numpy as np
arr_True = np.full((3,3), True, dtype=bool)
print(arr_True)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


* 2: 

In [19]:
arr_1D = np.array([0,1,2,3,4,5,6,7,8])

arr_2D = np.reshape(arr_1D, (3,3))
print('Arr_2D: ')
print(arr_2D,'\n') 

# Hoán đổi cột 1 cho cột 3: 
arr_2D[:,[0,2]] = arr_2D[:,[2,0]]
print('Arr_2D sau khi chuyển đổi cột 1 cho cột 3: ')
print(arr_2D,'\n')

# Hoán đổi cột 3 cho cột 1: 
arr_2D[:,[2,0]] = arr_2D[:,[0,2]]
print('Arr_2D sau khi chuyển đổi cột 3 cho cột 1: ')
print(arr_2D)


Arr_2D: 
[[0 1 2]
 [3 4 5]
 [6 7 8]] 

Arr_2D sau khi chuyển đổi cột 1 cho cột 3: 
[[2 1 0]
 [5 4 3]
 [8 7 6]] 

Arr_2D sau khi chuyển đổi cột 3 cho cột 1: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


- 3: 

In [20]:
# Chuyển cột 1 cho cột 2: 

arr_2D[:,[0,1]] = arr_2D[:,[1,0]]
print('Chuyển cột 1 sáng cột 2: ')
print(arr_2D)


Chuyển cột 1 sáng cột 2: 
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [21]:
# Chuyển cột 2 cho cột 1: 

arr_2D[:,[1,0]] = arr_2D[:,[0,1]]
print('Chuyển cột 1 sáng cột 2: ')
print(arr_2D)

Chuyển cột 1 sáng cột 2: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


- 4: 

In [22]:
# Chuyển các hàng với nhau: 
arr_2D[[0,1,2],:] = arr_2D[[2,1,0],:]
print(arr_2D)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


- 5: 


In [23]:
# Chuyển đảo các cột với nhau: 
arr_2D[:,[0,1,2]] = arr_2D[:,[2,1,0]]
print(arr_2D)

[[8 7 6]
 [5 4 3]
 [2 1 0]]


* 6: 

In [24]:
import numpy as np
arr_2D_null = np.array([[1,2,3], [np.nan,5,6], [7,np.nan,9], [4,5,6]])
print(f'Có gtr rỗng hay không: {arr_2D_null.any()}')

Có gtr rỗng hay không: True


* 7: 

In [25]:
arr_2D_null[np.isnan(arr_2D_null)] = 0 # Sẽ tạo ra một "mặt nạ" (mask) trả về True tại những chỗ có nan và False tại những chỗ có số.
print(arr_2D_null)

[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]


* Bài 3.7

In [26]:
import numpy as np
baseball_2d = []
with open('baseball.txt', 'r') as f: 
    for i in f:
        h, w = i.split()
        baseball_2d.append([float(h), float(w)])
print(baseball_2d)


        


[[71.0, 212.0], [68.0, 245.0], [77.0, 252.0], [79.0, 201.0], [75.0, 245.0], [72.0, 153.0], [77.0, 243.0], [69.0, 250.0], [71.0, 172.0], [74.0, 252.0], [67.0, 258.0], [71.0, 164.0], [75.0, 192.0], [75.0, 178.0], [72.0, 185.0], [69.0, 162.0], [68.0, 181.0], [72.0, 220.0], [72.0, 208.0], [67.0, 235.0], [70.0, 177.0], [69.0, 215.0], [66.0, 191.0], [72.0, 194.0], [76.0, 211.0], [78.0, 206.0], [70.0, 155.0], [66.0, 177.0], [80.0, 177.0], [76.0, 257.0], [69.0, 193.0], [65.0, 233.0], [76.0, 179.0], [74.0, 211.0], [70.0, 224.0], [77.0, 241.0], [76.0, 238.0], [73.0, 252.0], [65.0, 211.0], [75.0, 246.0], [75.0, 150.0], [79.0, 176.0], [74.0, 211.0], [80.0, 226.0], [76.0, 254.0], [76.0, 152.0], [80.0, 252.0], [79.0, 219.0], [78.0, 221.0], [78.0, 176.0], [79.0, 158.0], [78.0, 211.0], [67.0, 186.0], [76.0, 246.0], [71.0, 200.0], [68.0, 255.0], [80.0, 193.0], [73.0, 173.0], [67.0, 228.0], [69.0, 208.0], [67.0, 181.0], [71.0, 245.0], [69.0, 237.0], [73.0, 254.0], [71.0, 201.0], [66.0, 211.0], [68.0, 20

* 1: 


In [27]:
np_baseball = np.array(baseball_2d)
print(f'Kiểu dữ liệu : {np_baseball.dtype}','\n')

print(f'Kích thước mảng: {np_baseball.shape}')


Kiểu dữ liệu : float64 

Kích thước mảng: (200, 2)


- 2: 

In [28]:
# In các gtr  dòng 50 trong np_baseball: 
print('Các gtr củ dòng thứ 50: ')
print(np_baseball[50])


Các gtr củ dòng thứ 50: 
[ 79. 158.]


- 3: 

In [29]:
np_weights = np.array(np_baseball[:,1])
print('Data np_weights: ')
print(np_weights)


Data np_weights: 
[212. 245. 252. 201. 245. 153. 243. 250. 172. 252. 258. 164. 192. 178.
 185. 162. 181. 220. 208. 235. 177. 215. 191. 194. 211. 206. 155. 177.
 177. 257. 193. 233. 179. 211. 224. 241. 238. 252. 211. 246. 150. 176.
 211. 226. 254. 152. 252. 219. 221. 176. 158. 211. 186. 246. 200. 255.
 193. 173. 228. 208. 181. 245. 237. 254. 201. 211. 207. 201. 161. 188.
 151. 152. 250. 205. 230. 208. 151. 151. 241. 203. 236. 250. 245. 246.
 150. 168. 151. 202. 193. 239. 181. 219. 181. 217. 204. 224. 205. 166.
 187. 173. 218. 247. 219. 235. 160. 165. 246. 222. 208. 219. 229. 242.
 152. 169. 208. 185. 168. 239. 216. 168. 169. 245. 220. 201. 254. 182.
 189. 188. 231. 253. 150. 160. 241. 206. 238. 199. 172. 180. 243. 191.
 248. 156. 165. 239. 209. 151. 150. 197. 161. 218. 186. 181. 158. 254.
 248. 168. 197. 229. 152. 169. 173. 203. 182. 173. 224. 221. 185. 187.
 253. 233. 248. 238. 248. 174. 242. 167. 259. 231. 215. 203. 184. 229.
 210. 190. 249. 182. 217. 182. 163. 170. 197. 169. 157. 156

 - 4: 

In [30]:
# Cho biết chiều cao vận động viên thứ 124: 
np_heights = np.array(np_baseball[:,0])
print(f'Chiều cao vận dộng viên thứ 124: {np_heights[124]}')

Chiều cao vận dộng viên thứ 124: 69.0


- 5: 

In [31]:
# Cách 1: 
np_heights_tb = sum(np_heights) / len(np_heights)

# Cách 2: 
np_heights_mean = np.mean(np_heights)
print('Cách 1: ')
print(f'Chiều cao TB của các cầu thủ: {np_heights_tb}','\n')
print('Cách 2: ')
print(f'Chiều cao TB của các cầu thủ: {np_heights_mean}')

Cách 1: 
Chiều cao TB của các cầu thủ: 72.72 

Cách 2: 
Chiều cao TB của các cầu thủ: 72.72


In [32]:
# Cách 1: 
print('Cách 1: ')
np_weights_tb = sum(np_weights) / len(np_weights)
print(f'Cân nặng TB của cầu thủ: {np_weights_tb}','\n')

# Cách 2: 
print('Cách 2: ')
np_weights_mean = np.mean(np_weights)
print(f'Cân nặng TB của cầu thủ: {np_weights_mean}','\n')

Cách 1: 
Cân nặng TB của cầu thủ: 203.635 

Cách 2: 
Cân nặng TB của cầu thủ: 203.635 



* 6

In [33]:
import numpy as np
# Xét tương quan thuận nghịch giữ chiều cao và cân nặng các cầu thủ: 
r = np.corrcoef(np_weights, np_heights)[0,1]

if r > 0: 
    print('Tương quan thuận')
elif r < 0 : 
    print('Tương quan nghịch')
else:
    print('Không có tương quan')


Tương quan nghịch


* Bài: 3.8 

In [34]:
import numpy as np

# Chép dữ liệu từ 2 tập tin vào 2 list : 
heights = []
positions = []

# Chép file heights: 
with open('heights.txt', 'r') as f: 
    for line in f: 
        heights.append(float(line))


# Chép file positions : 
with open('positions.txt', 'r') as f : 
    for line in f : 
        positions.append(line.strip())
    

- 1: 

In [35]:
# a, : 
np_positions = np.array(positions)
print(f'Kiểu dữ liệu của mảng positions: {np_positions.dtype}','\n')

# b, : 
np_heights = np.array(heights)
print(f'Kiểu dữ liệu của mảng heights: {np_heights.dtype}')



Kiểu dữ liệu của mảng positions: <U2 

Kiểu dữ liệu của mảng heights: float64


- 2: 


In [36]:
# Chiều cao tb của các GK: 
gk = np.where(np_positions == 'GK')

heights_GK = np.mean(np_heights[gk])
print(f'Chiều cao trung bình của GK: {heights_GK:.2f}')

Chiều cao trung bình của GK: 183.67


- 3: 


In [37]:
# Chiều cao tb của M: 
m= np.where(np_positions == 'M')

heights_M = np.mean(np_heights[m])
print(f'Chiều cao trung bình của M: {heights_M:.2f}','\n')

# Chiều cao trung bình của A: 
a = np.where(np_positions == 'A')
heights_A = np.mean(np_heights[a])
print(f'Chiều cao trung bình của A: {heights_A:.2f}','\n')

# Chiều cao trung bình của D: 
d = np.where(np_positions == 'D')
heights_D = np.mean(np_heights[d])
print(f'Chiều cao trung bình D: {heights_D:.2f}')


Chiều cao trung bình của M: 179.86 

Chiều cao trung bình của A: 179.39 

Chiều cao trung bình D: 179.16


- 4: 

In [38]:
dtype = [('positions', 'U5'), ('heights', float)]

# Ghép dữ liệu thành structure array: 
player = np.zeros(len(positions), dtype=dtype)

player['positions'] = np_positions
player['heights'] = np_heights

print('Mảng Player: ','\n')
print(player)

Mảng Player:  

[('D', 200.) ('D', 167.) ('A', 161.) ('M', 177.) ('M', 175.) ('A', 174.)
 ('A', 168.) ('D', 166.) ('D', 194.) ('M', 165.) ('M', 197.) ('M', 187.)
 ('A', 162.) ('A', 161.) ('A', 165.) ('D', 173.) ('M', 174.) ('D', 192.)
 ('A', 198.) ('D', 161.) ('D', 195.) ('M', 172.) ('M', 194.) ('D', 186.)
 ('D', 174.) ('A', 188.) ('M', 197.) ('A', 177.) ('M', 160.) ('D', 170.)
 ('A', 187.) ('A', 181.) ('A', 177.) ('A', 169.) ('A', 173.) ('D', 181.)
 ('M', 166.) ('D', 165.) ('M', 184.) ('D', 166.) ('M', 182.) ('A', 182.)
 ('D', 198.) ('A', 176.) ('M', 162.) ('M', 189.) ('A', 194.) ('A', 167.)
 ('M', 184.) ('A', 165.) ('D', 195.) ('D', 178.) ('A', 200.) ('M', 199.)
 ('M', 183.) ('A', 196.) ('D', 172.) ('M', 164.) ('M', 162.) ('A', 174.)
 ('D', 178.) ('A', 165.) ('D', 174.) ('D', 166.) ('M', 184.) ('A', 177.)
 ('D', 189.) ('D', 200.) ('A', 183.) ('D', 170.) ('M', 183.) ('M', 182.)
 ('M', 173.) ('M', 177.) ('M', 164.) ('A', 198.) ('D', 200.) ('A', 170.)
 ('D', 194.) ('M', 175.) ('A', 170.

- 5: 


In [39]:
# Sắp xếp mảng player theo chiều cao từ tập đến cao :
player_sorted = np.sort(player['heights'])
print('Mảng player sắp xếp theo từ thấp đến cao: ','\n')
print(player_sorted,'\n')

# Sắp xếp mảng player theo chiều từ cao đến thấp: 
player_sorted_1 = np.sort(player['heights'])[::-1]

print('Mảng player được sắp xếp từ cao đến thấp: ','\n')
print(player_sorted_1)

Mảng player sắp xếp theo từ thấp đến cao:  

[160. 160. 160. 160. 160. 161. 161. 161. 161. 161. 162. 162. 162. 162.
 162. 163. 163. 163. 163. 164. 164. 164. 164. 164. 164. 164. 164. 164.
 165. 165. 165. 165. 165. 165. 165. 165. 166. 166. 166. 166. 166. 167.
 167. 167. 167. 167. 167. 167. 168. 168. 168. 168. 168. 169. 169. 169.
 169. 170. 170. 170. 170. 170. 170. 170. 170. 171. 172. 172. 172. 172.
 173. 173. 173. 173. 173. 173. 174. 174. 174. 174. 174. 174. 174. 174.
 174. 174. 174. 174. 175. 175. 175. 175. 175. 175. 175. 176. 176. 176.
 176. 176. 176. 177. 177. 177. 177. 177. 177. 177. 177. 177. 178. 178.
 178. 179. 179. 179. 180. 180. 180. 180. 181. 181. 181. 181. 181. 182.
 182. 182. 183. 183. 183. 183. 183. 183. 183. 184. 184. 184. 184. 184.
 184. 185. 185. 185. 185. 186. 187. 187. 187. 187. 187. 187. 188. 188.
 188. 189. 189. 189. 189. 189. 189. 190. 191. 191. 191. 191. 191. 192.
 192. 192. 192. 192. 192. 193. 193. 193. 193. 194. 194. 194. 194. 194.
 194. 194. 194. 194. 195. 195. 1

In [40]:
# Vị trí có chiều cao, cao nhất : 
max_heights = np.argmax(player['heights'])

print(f'Vị trí có chiều cao, cao nhất là: {max_heights}','\n')

min_heights = np.argmin(player['heights'])
print(f'Vị trí có chiều cao thấp nhất là : {min_heights}')


Vị trí có chiều cao, cao nhất là: 0 

Vị trí có chiều cao thấp nhất là : 28


- Bài 3.9: 

In [41]:
import numpy as np
# Lấy dữ liệu từ file euro2012.csv : 

np_euro2012_csv = np.genfromtxt('euro2012.csv', dtype= str, delimiter=",", skip_header=1)
print(np_euro2012_csv)

[['England' '5' '57' '5' '0']
 ['France' '3' '49' '6' '0']
 ['Germany' '10' '63' '4' '0']
 ['Portugal' '6' '55' '7' '0']
 ['Italy' '6' '50' '16' '0']
 ['Spain' '12' '68' '9' '1']
 ['Greece' '5' '44' '9' '0']
 ['Russia' '5' '47' '6' '1']
 ['Croatia' '4' '51' '7' '0']
 ['Ireland' '1' '35' '6' '0']
 ['Denmark' '4' '48' '5' '0']
 ['Netherlands' '2' '53' '6' '0']
 ['Sweden' '5' '46' '4' '0']
 ['Ukraine' '2' '42' '5' '0']
 ['Poland' '2' '39' '7' '0']
 ['Czech Republic' '4' '45' '8' '0']]


In [42]:
# Thông tin file euro2012: 
np_team = np.array(np_euro2012_csv[:,0])

np_goals = np.array(np_euro2012_csv[:,1]).astype(int)

np_Shooting_Accuracy = np.array(np_euro2012_csv[:,2]).astype(int)

np_Yellow_Cards = np.array(np_euro2012_csv[:,3]).astype(int)

np_Red_Cards = np.array(np_euro2012_csv[:,4]).astype(int)


# In thông tin ra ngoài : 
print(f'Kiểu dữ liệu của file euro_2012: {np_euro2012_csv.dtype}')
print(f'Kích cỡ mảng : {np_euro2012_csv.shape}','\n')


print('Danh sách các cột: ','\n')
print('Danh sách các đội tham dự: ','\n')
print(np_team,'\n')

print('Danh sách bàn thắng các đội: ','\n')
print(np_goals,'\n')

print('Danh sách độ chính xác khi sút: ','\n')
print(np_Shooting_Accuracy,'\n')

print('Danh sách the vàng của các đội: ','\n')
print(np_Yellow_Cards,'\n')

print('Danh sách thẻ đỏ của các đội: ','\n')
print(np_Red_Cards)








Kiểu dữ liệu của file euro_2012: <U14
Kích cỡ mảng : (16, 5) 

Danh sách các cột:  

Danh sách các đội tham dự:  

['England' 'France' 'Germany' 'Portugal' 'Italy' 'Spain' 'Greece' 'Russia'
 'Croatia' 'Ireland' 'Denmark' 'Netherlands' 'Sweden' 'Ukraine' 'Poland'
 'Czech Republic'] 

Danh sách bàn thắng các đội:  

[ 5  3 10  6  6 12  5  5  4  1  4  2  5  2  2  4] 

Danh sách độ chính xác khi sút:  

[57 49 63 55 50 68 44 47 51 35 48 53 46 42 39 45] 

Danh sách the vàng của các đội:  

[ 5  6  4  7 16  9  9  6  7  6  5  6  4  5  7  8] 

Danh sách thẻ đỏ của các đội:  

[0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0]


- 1: In gtri cột Goals:

In [43]:
print('In gtri cột Goals: ','\n')
print(np_goals)

In gtri cột Goals:  

[ 5  3 10  6  6 12  5  5  4  1  4  2  5  2  2  4]


- 2: Có bao nhiệu đội tham gia :

In [44]:
print('Số đội tham gia Euro 2012: ','\n')
print(len(np_team))



Số đội tham gia Euro 2012:  

16


- Yêu cầu 4: 

In [45]:
discipline = np_euro2012_csv[:,[0,1,3,4]]
print(discipline)


[['England' '5' '5' '0']
 ['France' '3' '6' '0']
 ['Germany' '10' '4' '0']
 ['Portugal' '6' '7' '0']
 ['Italy' '6' '16' '0']
 ['Spain' '12' '9' '1']
 ['Greece' '5' '9' '0']
 ['Russia' '5' '6' '1']
 ['Croatia' '4' '7' '0']
 ['Ireland' '1' '6' '0']
 ['Denmark' '4' '5' '0']
 ['Netherlands' '2' '6' '0']
 ['Sweden' '5' '4' '0']
 ['Ukraine' '2' '5' '0']
 ['Poland' '2' '7' '0']
 ['Czech Republic' '4' '8' '0']]


- Yêu cầu 5: 

In [46]:
# Sắp xếp Discipline giảm dần theo cột yellow_cards: 

a = discipline[:,2].astype(int)
sort_idx = np.argsort(-a)
print('Sắp xếp Discipline giảm dần theo cột yellow_cards: ','\n')
print(discipline[sort_idx],'\n')

# Sắp xếp Discipline giảm dần theo cột Reds_cards
b = discipline[:,3].astype(int)
sort_idx = np.argsort(-b)
print('Sắp xếp Discipline giảm dần theo cột red_cards: ','\n')
print(discipline[sort_idx])

Sắp xếp Discipline giảm dần theo cột yellow_cards:  

[['Italy' '6' '16' '0']
 ['Spain' '12' '9' '1']
 ['Greece' '5' '9' '0']
 ['Czech Republic' '4' '8' '0']
 ['Croatia' '4' '7' '0']
 ['Poland' '2' '7' '0']
 ['Portugal' '6' '7' '0']
 ['France' '3' '6' '0']
 ['Netherlands' '2' '6' '0']
 ['Ireland' '1' '6' '0']
 ['Russia' '5' '6' '1']
 ['England' '5' '5' '0']
 ['Ukraine' '2' '5' '0']
 ['Denmark' '4' '5' '0']
 ['Germany' '10' '4' '0']
 ['Sweden' '5' '4' '0']] 

Sắp xếp Discipline giảm dần theo cột red_cards:  

[['Russia' '5' '6' '1']
 ['Spain' '12' '9' '1']
 ['England' '5' '5' '0']
 ['France' '3' '6' '0']
 ['Portugal' '6' '7' '0']
 ['Germany' '10' '4' '0']
 ['Italy' '6' '16' '0']
 ['Greece' '5' '9' '0']
 ['Croatia' '4' '7' '0']
 ['Ireland' '1' '6' '0']
 ['Denmark' '4' '5' '0']
 ['Netherlands' '2' '6' '0']
 ['Sweden' '5' '4' '0']
 ['Ukraine' '2' '5' '0']
 ['Poland' '2' '7' '0']
 ['Czech Republic' '4' '8' '0']]


- Yêu cầu 6 :

In [47]:
# a, Tính trung bình thẻ vàng: 
print('Trung Bình thẻ vàng: ','\n')

print(np_Yellow_Cards.mean(),'\n')

# b, Lọc các đội ghi 6 bàn thắng: 
mask = np_euro2012_csv[:,1].astype(int) > 6
print('Đội ghi trên 6 bàn thắng: ','\n')
print(np_euro2012_csv[:,:2][mask])

Trung Bình thẻ vàng:  

6.875 

Đội ghi trên 6 bàn thắng:  

[['Germany' '10']
 ['Spain' '12']]


- Yêu cầu 7: 

In [48]:
mask_1 = [i.startswith('G') for i in np_team]
print()
print(np_team[mask_1])


['Germany' 'Greece']


**Yêu cầu 8:**

In [49]:
print('In 7 cột đầu của Euro12: ','\n')
print(np_euro2012_csv[:7,])

In 7 cột đầu của Euro12:  

[['England' '5' '57' '5' '0']
 ['France' '3' '49' '6' '0']
 ['Germany' '10' '63' '4' '0']
 ['Portugal' '6' '55' '7' '0']
 ['Italy' '6' '50' '16' '0']
 ['Spain' '12' '68' '9' '1']
 ['Greece' '5' '44' '9' '0']]


**Yêu cầu 9:**

In [50]:
# In tất cả các cột trừ  3 cột cuối: 
print(np_euro2012_csv[:,[0,1]])


[['England' '5']
 ['France' '3']
 ['Germany' '10']
 ['Portugal' '6']
 ['Italy' '6']
 ['Spain' '12']
 ['Greece' '5']
 ['Russia' '5']
 ['Croatia' '4']
 ['Ireland' '1']
 ['Denmark' '4']
 ['Netherlands' '2']
 ['Sweden' '5']
 ['Ukraine' '2']
 ['Poland' '2']
 ['Czech Republic' '4']]


**Yêu cầu 11:**

In [51]:
mask_2 = np.isin(np_euro2012_csv[:,0], ['England', 'Italy', 'Russia']) # Hàm ktr xem một gtri có năm trong ds hay không
print(np_euro2012_csv[:,[0,2]][mask_2])

[['England' '57']
 ['Italy' '50']
 ['Russia' '47']]


**Bài 3.10:**

In [52]:
import numpy as np
# Lấy file drink.csv: 
np_drink = np.genfromtxt('drinks.csv', dtype=str, delimiter=',', skip_header=0)


- 1: Đọc dữ liệ từ file drink.csv: 

In [53]:
print(f'Kiểu dữ liệu của mảng Drink: {np_drink.dtype}','\n')
print(f'Kích thước của mảng Drink: {np_drink.shape}','\n')
print('Hiểu thị tên các cột của Drink: ','\n')
print(np_drink[0,:],'\n')

print('Xem 5 dòng đầu tiền của Drink: ','\n')
print(np_drink[1:6,:],'\n')


print('Xem 5 dòng cuối của Drink: ','\n')
print(np_drink[-5:,])

''' Chú thích:
- 1. country : Quốc gia
- 2. beer_servings : Lượng bia tiêu thụ (đơn vị: servings/năm/người)
- 3. spirit_servings : Lượng rượu mạnh tiêu thụ (servings/năm/người)
- 4. wine_servings : Lượng rượu vang tiêu thụ (servings/năm/người)
- 5. total_litres_of_pure_alcohol : Lượng cồn nguyên chất tiêu thụ (lít/năm/người)
- 6. continent : Châu lục
'''





Kiểu dữ liệu của mảng Drink: <U28 

Kích thước của mảng Drink: (37, 6) 

Hiểu thị tên các cột của Drink:  

['country' 'beer_servings' 'spirit_servings' 'wine_servings'
 'total_litres_of_pure_alcohol' 'continent'] 

Xem 5 dòng đầu tiền của Drink:  

[['Afghanistan' '0' '0' '0' '0.0' 'Asia']
 ['Albania' '89' '132' '54' '4.9' 'Europe']
 ['Algeria' '25' '14' '14' '0.7' 'Africa']
 ['Argentina' '193' '25' '221' '8.3' 'South America']
 ['Australia' '261' '72' '212' '10.4' 'Oceania']] 

Xem 5 dòng cuối của Drink:  

[['Sweden' '152' '60' '186' '7.2' 'Europe']
 ['Thailand' '99' '101' '1' '4.6' 'Asia']
 ['United Kingdom' '219' '126' '195' '10.4' 'Europe']
 ['United States' '249' '158' '84' '9.2' 'North America']
 ['Vietnam' '168' '2' '1' '3.8' 'Asia']]


' Chú thích:\n- 1. country : Quốc gia\n- 2. beer_servings : Lượng bia tiêu thụ (đơn vị: servings/năm/người)\n- 3. spirit_servings : Lượng rượu mạnh tiêu thụ (servings/năm/người)\n- 4. wine_servings : Lượng rượu vang tiêu thụ (servings/năm/người)\n- 5. total_litres_of_pure_alcohol : Lượng cồn nguyên chất tiêu thụ (lít/năm/người)\n- 6. continent : Châu lục\n'

- 2: Cho biết số lượng bia tiêu thụ trung bình ở mỗi châu lục

In [54]:
# Yêu cầu 3: 
print('Thông tin lượng rượu vang tiêu thị ở mỗi châu lục: ','\n')
print(np_drink[1:,[0,3]])

Thông tin lượng rượu vang tiêu thị ở mỗi châu lục:  

[['Afghanistan' '0']
 ['Albania' '54']
 ['Algeria' '14']
 ['Argentina' '221']
 ['Australia' '212']
 ['Austria' '191']
 ['Bangladesh' '0']
 ['Belgium' '212']
 ['Brazil' '16']
 ['Canada' '100']
 ['Chile' '172']
 ['China' '8']
 ['Colombia' '3']
 ['Czech Republic' '134']
 ['Denmark' '278']
 ['Egypt' '1']
 ['Finland' '97']
 ['France' '370']
 ['Germany' '175']
 ['Greece' '218']
 ['India' '0']
 ['Indonesia' '0']
 ['Ireland' '165']
 ['Italy' '237']
 ['Japan' '27']
 ['Mexico' '5']
 ['New Zealand' '197']
 ['Nigeria' '0']
 ['Russia' '73']
 ['South Africa' '46']
 ['Spain' '312']
 ['Sweden' '186']
 ['Thailand' '1']
 ['United Kingdom' '195']
 ['United States' '84']
 ['Vietnam' '1']]


In [128]:
# Yêu cầu 4: 

# Europe:
print('========================================= Europe ========================================================')
mask_europe_beer = np_drink[1:,5]=='Europe'
europe_beer = np.array(np_drink[1:,1][mask_europe_beer])


print(f'Lượng tiêu thu bia trung bình của Europe là: {europe_beer.astype(float).mean():.2f}','\n')

mask_europe_spirit = np_drink[1:,5] == 'Europe'
europe_spirit = np.array(np_drink[1:,2][mask_europe_spirit])

print(f'Lượng tiêu thu rượu mạnh trung bình của Europe là: {europe_spirit.astype(float).mean():.2f}','\n')

mask_europe_wine = np_drink[1:,5] == 'Europe'
europe_wine = np.array(np_drink[1:,3][mask_europe_wine])

print(f'Lượng tiêu thu rượu vang trung bình của Europe là: {europe_wine.astype(float).mean():.2f}','\n')
print('==========================================================================================================','\n')

# Asia : 

print('=========================================== Asia =====================================================') 

mask_asia_beer = np_drink[1:,5]=='Asia'
asia_beer = np.array(np_drink[1:,1][mask_asia_beer])

print(f'Lượng tiêu thu bia trung bình của Asia là: {asia_beer.astype(float).mean():.2f}','\n')

mask_asia_spirit = np_drink[1:,5]=='Asia'
asia_spirit = np.array(np_drink[1:,2][mask_asia_spirit])

print(f'Lượng tiêu thu rượu mạnh trung bình của Asia là: {asia_spirit.astype(float).mean():.2f}','\n')

mask_asia_wine = np_drink[1:,5]=='Asia'
asia_wine = np.array(np_drink[1:,3][mask_asia_wine])

print(f'Lượng tiêu thu rượu vang trung bình của Asia là: {asia_wine.astype(float).mean():.2f}','\n')
print('=======================================================================================================','\n')

# Africa: 

print('=========================================== Africa =====================================================') 

mask_africa_beer = np_drink[1:,5]=='Africa'
africa_beer = np.array(np_drink[1:,1][mask_africa_beer])

print(f'Lượng tiêu thu bia trung bình của Africa là: {africa_beer.astype(float).mean():.2f}','\n')

mask_africa_spirit = np_drink[1:,5]=='Africa'
africa_spirit = np.array(np_drink[1:,2][mask_africa_spirit])

print(f'Lượng tiêu thu rượu mạnh trung bình của Africa là: {africa_spirit.astype(float).mean():.2f}','\n')

mask_africa_wine = np_drink[1:,5]=='Africa'
africa_wine = np.array(np_drink[1:,3][mask_africa_wine])

print(f'Lượng tiêu thu rượu vang trung bình của Africa là: {africa_wine.astype(float).mean():.2f}','\n')
print('=======================================================================================================','\n')


# South America: 
print('============================================ South America=============================================')
mask_South_America_beer = np_drink[1:,5]=='South America'
South_America_beer = np.array(np_drink[1:,1][mask_South_America_beer])

print(f'Lượng tiêu thu bia trung bình của South America là: {South_America_beer.astype(float).mean():.2f}','\n')

mask_South_America_spirit = np_drink[1:,5]=='South America'
South_America_spirit = np.array(np_drink[1:,2][mask_South_America_spirit])

print(f'Lượng tiêu thu rượu mạnh trung bình của South America là: {South_America_spirit.astype(float).mean():.2f}','\n')

mask_South_America_wine = np_drink[1:,5]=='South America'
South_America_wine = np.array(np_drink[1:,3][mask_South_America_wine])

print(f'Lượng tiêu thu rượu vang trung bình của South America là: {South_America_wine.astype(float).mean():.2f}','\n')
print('==========================================================================================================','\n')

# Oceania: 
print('============================================ Oceania =============================================')
mask_Oceania_beer = np_drink[1:,5]=='Oceania'
Oceania_beer = np.array(np_drink[1:,1][mask_Oceania_beer])

print(f'Lượng tiêu thu bia trung bình của Oceania là: {Oceania_beer.astype(float).mean():.2f}','\n')

mask_Oceania_spirit = np_drink[1:,5]=='Oceania'
Oceania_spirit = np.array(np_drink[1:,2][mask_Oceania_spirit])

print(f'Lượng tiêu thu rượu mạnh trung bình của Oceania là: {Oceania_spirit.astype(float).mean():.2f}','\n')

mask_Oceania_wine = np_drink[1:,5]=='Oceania'
Oceania_wine = np.array(np_drink[1:,3][mask_Oceania_wine])

print(f'Lượng tiêu thu rượu vang trung bình của Oceania là: {Oceania_wine.astype(float).mean():.2f}','\n')
print('==========================================================================================================','\n')

# North America: 
print('============================================ North America =============================================')
mask_North_America_beer = np_drink[1:,5]=='North America'
North_America_beer = np.array(np_drink[1:,1][mask_North_America_beer])

print(f'Lượng tiêu thu bia trung bình của North America là: {North_America_beer.astype(float).mean():.2f}','\n')

mask_North_America_spirit = np_drink[1:,5]=='North America'
North_America_spirit = np.array(np_drink[1:,2][mask_North_America_spirit])

print(f'Lượng tiêu thu rượu mạnh trung bình của North America là: {North_America_spirit.astype(float).mean():.2f}','\n')

mask_North_America_wine = np_drink[1:,5]=='North America'
North_America_wine = np.array(np_drink[1:,3][mask_North_America_wine])

print(f'Lượng tiêu thu rượu vang trung bình của North America là: {North_America_wine.astype(float).mean():.2f}','\n')
print('==========================================================================================================','\n')



========================================= Europe ========================================================
Lượng tiêu thu bia trung bình của Europe là: 227.80 

Lượng tiêu thu rượu mạnh trung bình của Europe là: 121.80 

Lượng tiêu thu rượu vang trung bình của Europe là: 193.13 


=========================================== Asia =====================================================
Lượng tiêu thu bia trung bình của Asia là: 54.12 

Lượng tiêu thu rượu mạnh trung bình của Asia là: 24.12 

Lượng tiêu thu rượu vang trung bình của Asia là: 4.62 


=========================================== Africa =====================================================
Lượng tiêu thu bia trung bình của Africa là: 74.50 

Lượng tiêu thu rượu mạnh trung bình của Africa là: 37.50 

Lượng tiêu thu rượu vang trung bình của Africa là: 15.25 


============================================ South America=============================================
Lượng tiêu thu bia trung bình của South America là: 181.75 

Lượng tiê

In [ ]:
# Yêu cầu 5: 
# Yêu cầu 4: 

# Europe:
print('========================================= Europe ========================================================')
mask_europe_beer = np_drink[1:,5]=='Europe'
europe_beer = np.array(np_drink[1:,1][mask_europe_beer])


print(f'Trung vị lượng tiêu thu bia của Europe là: {np.median(europe_beer.astype(float)):.2f}','\n')

mask_europe_spirit = np_drink[1:,5] == 'Europe'
europe_spirit = np.array(np_drink[1:,2][mask_europe_spirit])

print(f'Trung vị lượng tiêu thu rượu mạnh của Europe là: {np.median(europe_spirit.astype(float)):.2f}','\n')

mask_europe_wine = np_drink[1:,5] == 'Europe'
europe_wine = np.array(np_drink[1:,3][mask_europe_wine])

print(f'Trung vị lượng tiêu thu rượu vang của Europe là: {np.median(europe_wine.astype(float)):.2f}','\n')
print('==========================================================================================================','\n')

# Asia : 

print('=========================================== Asia =====================================================') 

mask_asia_beer = np_drink[1:,5]=='Asia'
asia_beer = np.array(np_drink[1:,1][mask_asia_beer])

print(f'Trung vị lượng tiêu thu bia của Asia là: {np.median(asia_beer.astype(float)):.2f}','\n')

mask_asia_spirit = np_drink[1:,5]=='Asia'
asia_spirit = np.array(np_drink[1:,2][mask_asia_spirit])

print(f'Trung vị lượng tiêu thu rượu mạnh của Asia là: {np.median(asia_spirit.astype(float)):.2f}','\n')

mask_asia_wine = np_drink[1:,5]=='Asia'
asia_wine = np.array(np_drink[1:,3][mask_asia_wine])

print(f'Trung vị lượng tiêu thu rượu vang của Asia là: {np.median(asia_wine.astype(float)):.2f}','\n')
print('=======================================================================================================','\n')

# Africa: 

print('=========================================== Africa =====================================================') 

mask_africa_beer = np_drink[1:,5]=='Africa'
africa_beer = np.array(np_drink[1:,1][mask_africa_beer])

print(f'Trung vị lượng tiêu thu bia của Africa là: {np.median(africa_beer.astype(float)):.2f}','\n')

mask_africa_spirit = np_drink[1:,5]=='Africa'
africa_spirit = np.array(np_drink[1:,2][mask_africa_spirit])

print(f'Trung vị lượng tiêu thu rượu mạnh của Africa là: {np.median(africa_spirit.astype(float)):.2f}','\n')

mask_africa_wine = np_drink[1:,5]=='Africa'
africa_wine = np.array(np_drink[1:,3][mask_africa_wine])

print(f'Trung vị lượng tiêu thu rượu vang của Africa là: {np.median(africa_wine.astype(float)):.2f}','\n')
print('=======================================================================================================','\n')


# South America: 
print('============================================ South America=============================================')
mask_South_America_beer = np_drink[1:,5]=='South America'
South_America_beer = np.array(np_drink[1:,1][mask_South_America_beer])

print(f'Trung vị lượng tiêu thu bia của South America là: {np.median(South_America_beer.astype(float)):.2f}','\n')

mask_South_America_spirit = np_drink[1:,5]=='South America'
South_America_spirit = np.array(np_drink[1:,2][mask_South_America_spirit])

print(f'Trung vị lượng tiêu thu rượu mạnh của South America là: {np.median(South_America_spirit.astype(float)):.2f}','\n')

mask_South_America_wine = np_drink[1:,5]=='South America'
South_America_wine = np.array(np_drink[1:,3][mask_South_America_wine])

print(f'Trung vị lượng tiêu thu rượu vang của South America là: {np.median(South_America_wine.astype(float)):.2f}','\n')
print('==========================================================================================================','\n')

# Oceania: 
print('============================================ Oceania =============================================')
mask_Oceania_beer = np_drink[1:,5]=='Oceania'
Oceania_beer = np.array(np_drink[1:,1][mask_Oceania_beer])

print(f'Trung vị lượng tiêu thu bia của Oceania là: {np.median(Oceania_beer.astype(float)):.2f}','\n')

mask_Oceania_spirit = np_drink[1:,5]=='Oceania'
Oceania_spirit = np.array(np_drink[1:,2][mask_Oceania_spirit])

print(f'Trung vị lượng tiêu thu rượu mạnh của Oceania là: {np.median(Oceania_spirit.astype(float)):.2f}','\n')

mask_Oceania_wine = np_drink[1:,5]=='Oceania'
Oceania_wine = np.array(np_drink[1:,3][mask_Oceania_wine])

print(f'Trung vị lượng tiêu thu rượu vang của Oceania là: {np.median(Oceania_wine.astype(float)):.2f}','\n')
print('==========================================================================================================','\n')

# North America: 
print('============================================ North America =============================================')
mask_North_America_beer = np_drink[1:,5]=='North America'
North_America_beer = np.array(np_drink[1:,1][mask_North_America_beer])

print(f'Trung vị lượng tiêu thu bia của North America là: {np.median(North_America_beer.astype(float)):.2f}','\n')

mask_North_America_spirit = np_drink[1:,5]=='North America'
North_America_spirit = np.array(np_drink[1:,2][mask_North_America_spirit])

print(f'Trung vị lượng tiêu thu rượu mạnh của North America là: {np.median(North_America_spirit.astype(float)):.2f}','\n')

mask_North_America_wine = np_drink[1:,5]=='North America'
North_America_wine = np.array(np_drink[1:,3][mask_North_America_wine])

print(f'Trung vị lượng tiêu thu rượu vang của North America là: {np.median(North_America_wine.astype(float)):.2f}','\n')
print('==========================================================================================================','\n')



In [131]:
# Yêu cầu 6: 

# Europe: 
mask_europe = np_drink[1:,5] == 'Europe'
arr_spirit_europe = (np_drink[1:,][mask_europe])
max_europe = np.argmax(arr_spirit_europe[:,2].astype(int))
min_europe = np.argmin(arr_spirit_europe[:,2].astype(int))
print('Lương tiêu thụ rượu mạnh ở Europe: ','\n')
print(f'Lượng tiêu thụ trung bình: {europe_spirit.astype(float).mean():.2f}')
print(f'Nước có lượng tiêu thụ rượu mạnh lớn nhất ở Europe: {arr_spirit_europe[:,[0,2,5]][max_europe]}')
print(f'Nước có lượng tiêu thụ rượu mạnh lớn nhỏ nhất ở Europe: {arr_spirit_europe[:,[0,2,5]][min_europe]}','\n')


# Asia: 
mask_asia = np_drink[1:,5] == 'Asia'
arr_spirit_asia = (np_drink[1:,][mask_asia])
max_asia = np.argmax(arr_spirit_asia[:,2].astype(int))
min_asia = np.argmin(arr_spirit_asia[:,2].astype(int))
print('Lương tiêu thụ rượu mạnh ở Asia: ','\n')
print(f'Lượng tiêu thụ trung bình: {asia_spirit.astype(float).mean():.2f}')
print(f'Nước có lượng tiêu thụ rượu mạnh lớn nhất ở Asia: {arr_spirit_asia[:,[0,2,5]][max_asia]}')
print(f'Nước có lượng tiêu thụ rượu mạnh lớn nhỏ nhất ở Asia: {arr_spirit_asia[:,[0,2,5]][min_asia]}','\n')

# Africa: 

mask_africa = np_drink[1:,5] == 'Africa'
arr_spirit_africa = (np_drink[1:,][mask_africa])
max_africa = np.argmax(arr_spirit_africa[:,2].astype(int))
min_africa = np.argmin(arr_spirit_africa[:,2].astype(int))
print('Lương tiêu thụ rượu mạnh ở Africa: ','\n')
print(f'Lượng tiêu thụ trung bình: {africa_spirit.astype(float).mean():.2f}')
print(f'Nước có lượng tiêu thụ rượu mạnh lớn nhất ở Africa: {arr_spirit_africa[:,[0,2,5]][max_africa]}')
print(f'Nước có lượng tiêu thụ rượu mạnh lớn nhỏ nhất ở Africa: {arr_spirit_africa[:,[0,2,5]][min_asia]}','\n')

# South America: 

mask_south_america = np_drink[1:,5] == 'South America'
arr_spirit_south_america = (np_drink[1:,][mask_south_america])
max_south_america = np.argmax(arr_spirit_south_america[:,2].astype(int))
min_south_america = np.argmin(arr_spirit_south_america[:,2].astype(int))
print('Lương tiêu thụ rượu mạnh ở South America: ', '\n')
print(f'Lượng tiêu thụ trung bình: {South_America_spirit.astype(float).mean():.2f}')
print(f'Nước có lượng tiêu thụ rượu mạnh lớn nhất ở South America: {arr_spirit_south_america[:,[0,2,5]][max_south_america]}')
print(f'Nước có lượng tiêu thụ rượu mạnh lớn nhỏ nhất ở South America: {arr_spirit_south_america[:,[0,2,5]][min_south_america]}','\n')

# Oceania: 

mask_Oceania = np_drink[1:,5] == 'Oceania'
arr_spirit_Oceania = (np_drink[1:,][mask_Oceania])
max_Oceania = np.argmax(arr_spirit_Oceania[:,2].astype(int))
min_Oceania= np.argmin(arr_spirit_Oceania[:,2].astype(int))
print('Lương tiêu thụ rượu mạnh ở Oceania: ', '\n')
print(f'Lượng tiêu thụ trung bình: {Oceania_spirit.astype(float).mean():.2f}')
print(f'Nước có lượng tiêu thụ rượu mạnh lớn nhất ở South America: {arr_spirit_Oceania[:,[0,2,5]][max_Oceania]}')
print(f'Nước có lượng tiêu thụ rượu mạnh lớn nhỏ nhất ở South America: {arr_spirit_Oceania[:,[0,2,5]][min_Oceania]}','\n') 

# North America: 

mask_north_america = np_drink[1:,5] == 'North America'
arr_spirit_north_america = (np_drink[1:,][mask_north_america])
max_north_america = np.argmax(arr_spirit_north_america[:,2].astype(int))
min_north_america= np.argmin(arr_spirit_north_america[:,2].astype(int))
print('Lương tiêu thụ rượu mạnh ở North America: ', '\n')
print(f'Lượng tiêu thụ trung bình: {North_America_spirit.astype(float).mean():.2f}')
print(f'Nước có lượng tiêu thụ rượu mạnh lớn nhất ở North America: {arr_spirit_north_america[:,[0,2,5]][max_north_america]}')
print(f'Nước có lượng tiêu thụ rượu mạnh lớn nhỏ nhất ở North America: {arr_spirit_north_america[:,[0,2,5]][min_north_america]}','\n') 






Lương tiêu thụ rượu mạnh ở Europe:  

Lượng tiêu thụ trung bình: 121.80
Nước có lượng tiêu thụ rượu mạnh lớn nhất ở Europe: ['Russia' '326' 'Europe']
Nước có lượng tiêu thụ rượu mạnh lớn nhỏ nhất ở Europe: ['Italy' '42' 'Europe'] 

Lương tiêu thụ rượu mạnh ở Asia:  

Lượng tiêu thụ trung bình: 24.12
Nước có lượng tiêu thụ rượu mạnh lớn nhất ở Asia: ['Thailand' '101' 'Asia']
Nước có lượng tiêu thụ rượu mạnh lớn nhỏ nhất ở Asia: ['Afghanistan' '0' 'Asia'] 

Lương tiêu thụ rượu mạnh ở Africa:  

Lượng tiêu thụ trung bình: 37.50
Nước có lượng tiêu thụ rượu mạnh lớn nhất ở Africa: ['South Africa' '76' 'Africa']
Nước có lượng tiêu thụ rượu mạnh lớn nhỏ nhất ở Africa: ['Algeria' '14' 'Africa'] 

Lương tiêu thụ rượu mạnh ở South America:  

Lượng tiêu thụ trung bình: 92.50
Nước có lượng tiêu thụ rượu mạnh lớn nhất ở South America: ['Brazil' '145' 'South America']
Nước có lượng tiêu thụ rượu mạnh lớn nhỏ nhất ở South America: ['Argentina' '25' 'South America'] 

Lương tiêu thụ rượu mạnh ở Ocean

In [155]:
# Yêu cầu 7: 
idx_a = np_drink[1:,1].astype(int)
sort_idx = np.argsort(idx_a)
sort_values = np_drink[1:,][sort_idx]

print('Top 5 quốc gia có lượng tiêu thụ bia ít nhất: ','\n')
print(sort_values[:5,[0,1,5]],'\n')

print('Top 5 quốc gia có lượng tiêu thụ bia nhiều nhất: ','\n')
print(sort_values[-5:,[0,1,5]])




Top 5 quốc gia có lượng tiêu thụ bia ít nhất:  

[['Afghanistan' '0' 'Asia']
 ['Bangladesh' '0' 'Asia']
 ['Indonesia' '1' 'Asia']
 ['Egypt' '6' 'Africa']
 ['India' '9' 'Asia']] 

Top 5 quốc gia có lượng tiêu thụ bia nhiều nhất:  

[['Spain' '284' 'Europe']
 ['Belgium' '295' 'Europe']
 ['Ireland' '313' 'Europe']
 ['Germany' '346' 'Europe']
 ['Czech Republic' '361' 'Europe']]
